export const rulesFul = [
    { title:"Неправильное использование дефиса", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неправильное использование короткого тире", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неправильное использование длинного тире", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неправильное использование закрывающей кавычки", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неправильное использование открывающей кавычки", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неправильное оформление нескольких ссылок", description:"Несколько ссылок подряд следует оформлять так [0,1], а не [0] [1]"},
    { title:"Отсутствует пробел с внешней стороны скобок", description:"С внешней стороны скобки следует ставить пробел (вот так) вот"},
    { title:"Некорректное цитирование", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Нумерация секций не должна начинаться с нуля", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Большая русская буква после скобки", description:"После скобки следует ставить маленькую букву, если речь идет не о названиях"},
    { title:"Одна подсекция в секции", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Введение, заключение и список литературы не нумеруются", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"слова theorem, definition, lemma не должны использоваться", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неправильное написание аббревиатуры вуз", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Ссылки разных видов", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Использованы различные версии сокращения", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},
    { title:"Неверный порядок секций", description:"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"},  
    { title:"Символ ? в ссылке на литературу", description:"Целые числа от 1 до 9 следует писать словами"},
    { title:"Символы :, ., , в названии секции", description:"Целые числа от 1 до 9 следует писать словами"},
    { title:"Сокращённая ссылка", description:"Целые числа от 1 до 9 следует писать словами"},
    { title:"Неверный порядок ссылок на литературу", description:"Целые числа от 1 до 9 следует писать словами"},
    { title:"Неправильное написание целых чисел от 1 до 9", description:"Целые числа от 1 до 9 следует писать словами"},
    { title:"Слово вышло за поля", description:"Целые числа от 1 до 9 следует писать словами"},
  ];